[package]
name = "langchain"
version = "0.1.0"
edition = "2024"

[dependencies]
langgraph = { path = "../langgraph" }
async-trait = { workspace = true }
langgraph_macro = { path = "../langgraph/macro" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
